-- Applywise schema
-- Run this whole file in the Supabase SQL Editor for a NEW project.
-- If the table already exists, run only the ALTER TABLE block at the bottom.

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  company text not null,
  role text not null,
  status text not null check (status in ('Applied', 'Interview', 'Offer', 'Rejected')),
  date date not null,
  next_step text default '',
  salary text default '',
  job_url text default '',
  interview_date date,
  notes text default '',
  created_at timestamptz not null default now()
);

alter table public.applications enable row level security;

-- Policies (no-ops if they already exist)
do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Users can view their own applications') then
    create policy "Users can view their own applications"
    on public.applications for select
    using (auth.uid() = user_id);
  end if;

  if not exists (select 1 from pg_policies where policyname = 'Users can add their own applications') then
    create policy "Users can add their own applications"
    on public.applications for insert
    with check (auth.uid() = user_id);
  end if;

  if not exists (select 1 from pg_policies where policyname = 'Users can update their own applications') then
    create policy "Users can update their own applications"
    on public.applications for update
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
  end if;

  if not exists (select 1 from pg_policies where policyname = 'Users can delete their own applications') then
    create policy "Users can delete their own applications"
    on public.applications for delete
    using (auth.uid() = user_id);
  end if;
end $$;

-- ---------------------------------------------------------------
-- Migration for EXISTING tables: adds the new columns if missing.
-- Safe to run repeatedly.
-- ---------------------------------------------------------------
alter table public.applications add column if not exists salary text default '';
alter table public.applications add column if not exists job_url text default '';
alter table public.applications add column if not exists interview_date date;
alter table public.applications add column if not exists notes text default '';