create table public.applications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  company text not null,
  role text not null,
  status text not null check (status in ('Applied', 'Interview', 'Offer', 'Rejected')),
  date date not null,
  next_step text default '',
  created_at timestamptz not null default now()
);

alter table public.applications enable row level security;

create policy "Users can view their own applications"
on public.applications for select
using (auth.uid() = user_id);

create policy "Users can add their own applications"
on public.applications for insert
with check (auth.uid() = user_id);

create policy "Users can update their own applications"
on public.applications for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own applications"
on public.applications for delete
using (auth.uid() = user_id);
